apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: k8-org
spec:
  selector:
      matchLabels:
        app: sales
  replicas: 1
  template:
      metadata:
        labels:
            app: sales
      spec:
        containers:
        - name: sales
          image:  msdemoregistry.azurecr.io/k8_sales:1.00
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /health
          livenessProbe:
            httpGet:
              port: 80
              path: /health
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: k8-org
spec:
  selector:
    app: sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP      