apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: k8-org
spec:
  selector:
      matchLabels:
        app: web
  replicas: 1
  template:
      metadata:
        labels:
            app: web
      spec:
        containers:
        - name: web
          image:  msdemoregistry.azurecr.io/k8_web:1.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /healthcheck
          livenessProbe:
            httpGet:
              port: 80
              path: /healthcheck
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: k8-org
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer      